# Site settings
title: Agnes McFarlin Data Scientist
description: Agnes McFarlin Data Scientist
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
username: Agnes McFarlin
user_description: Data Scientist with experience building and testing Machine Learning Models.
user_title: Data Scientist
email: amcfarlin1991@gmail.com
github_username:  https://github.com/oohtmeel1



# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
